/**
 * pixpec-text.slint generator.
 *
 * Mirrors the panda backend's per-font Y-shift calibration (each font's
 * meta.toml `[yShift]` table aggregated by danah/scripts into
 * `__pixpec-fonts.json`). For Slint we can't apply runtime
 * `transform: translateY(...)` — the software renderer doesn't support
 * 2D transforms — so we emit a `PixpecText` component that wraps a
 * `Text` and offsets it via explicit y inside a Rectangle wrapper, the
 * only Slint pattern that survives layout-positioning of the wrapper
 * while letting the inner Text move freely. The shift table compiles
 * to an if-chain on (font-family, font-size).
 *
 * Output is a single .slint module to be imported alongside tokens.slint.
 *
 * Why generate vs hand-author: the per-font calibration table changes
 * whenever a new fontSize is calibrated (via breakdown sweep). Driving
 * it from the same JSON the panda backend already consumes keeps both
 * targets in lockstep — no chance of one backend learning a new value
 * the other misses.
 */

export interface PixpecFontsInput {
  fonts: Array<{
    family: string
    /** Keys: device-px font size at outputScale (matches panda's verify-
     *  mode computed CSS fontSize). Values: device-px Y translation. */
    yShift?: Record<string, number>
  }>
}

export interface BuildTextOptions {
  /** Render scale used to read the keys/values of yShift. Both sides of
   *  the table are device-px; we divide both by `outputScale` to get the
   *  design-px font-size and design-px shift the Slint component needs. */
  outputScale?: number
  /** Component name to export. Defaults to `PixpecText`. */
  componentName?: string
}

export function buildPixpecText(input: PixpecFontsInput, opts: BuildTextOptions = {}): string {
  const scale = opts.outputScale ?? 8
  const componentName = opts.componentName ?? 'PixpecText'

  const fonts = input.fonts.filter((f) => f.yShift && Object.keys(f.yShift).length > 0)

  const lines: string[] = []
  lines.push('// AUTO-GENERATED by pixpec slint emitter (build-text).')
  lines.push('// Do not edit by hand. Regenerate from __pixpec-fonts.json.')
  lines.push('')
  lines.push(`export component ${componentName} {`)
  lines.push('    in property <string> text;')
  lines.push('    in property <length> font-size;')
  lines.push('    in property <int> font-weight;')
  lines.push('    in property <string> font-family;')
  lines.push('    in property <brush> text-color;')
  lines.push('    /** When >0, fixes the inner Text width (figma autoResize=fixed-width). */')
  lines.push('    in property <length> text-width: 0px;')
  lines.push('')
  lines.push('    function shift() -> length {')
  for (const f of fonts) {
    lines.push(`        if (root.font-family == "${f.family}") {`)
    const entries = Object.entries(f.yShift!)
      .map(([k, v]) => ({ devicePx: parseFloat(k), shift: v }))
      .filter((e) => Number.isFinite(e.devicePx))
      .sort((a, b) => a.devicePx - b.devicePx)
    for (const e of entries) {
      const designFs = e.devicePx / scale
      const designShift = e.shift / scale
      lines.push(`            if (root.font-size == ${designFs}px) { return ${designShift}px; }`)
    }
    lines.push('        }')
  }
  lines.push('        return 0px;')
  lines.push('    }')
  lines.push('')
  lines.push('    // Hug the inner Text\'s natural size — Rectangle base sizes from')
  lines.push('    // children when no explicit dim, so PixpecText behaves like a bare')
  lines.push('    // Text under HorizontalLayout sizing.')
  lines.push('    min-width: root.text-width > 0px ? root.text-width : txt.preferred-width;')
  lines.push('    min-height: txt.preferred-height;')
  lines.push('')
  lines.push('    txt := Text {')
  lines.push('        width: root.text-width > 0px ? root.text-width : self.preferred-width;')
  lines.push('        x: (parent.width - self.width) / 2;')
  lines.push('        y: (parent.height - self.height) / 2 + root.shift();')
  lines.push('        text: root.text;')
  lines.push('        font-family: root.font-family;')
  lines.push('        font-size: root.font-size;')
  lines.push('        font-weight: root.font-weight;')
  lines.push('        color: root.text-color;')
  lines.push('        horizontal-alignment: center;')
  lines.push('        vertical-alignment: center;')
  lines.push('    }')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}
