/**
 * Slint emitter — Design AST → .slint source.
 *
 * Entry point. Dispatches to per-node-kind lowering modules
 * (lower-flex.ts / lower-box.ts / lower-text.ts), wraps the result in a
 * `Window` element with the PoC-derived render contract, and serialises
 * the IR to text via `ir.ts`.
 *
 * Render contract (PoC-derived; see slint-poc/work for the chip baseline):
 *   - The component inherits Window with `background: white` — the slint
 *     software renderer treats `transparent` Window as black-fill, so we
 *     lock white to match measure-rs's white-composite path.
 *   - Tokens are referenced via `Tokens.<kebab-id>` against a sibling
 *     tokens.slint module (built by `build-tokens.ts`). Caller supplies
 *     `tokensImportPath` when the AST references token paths.
 *
 * Out of scope (deferred — surface via breakdown):
 *   DShape / DVector / DImage / DInstance / DUnknown,
 *   variants & prop bindings, Sizing semantics beyond width/height,
 *   absolute positioning, opacity, rotation, border, line-height
 *   enforcement.
 */

import { type DNode, type DFlex, type DStack, type DBox, type DText, NodeKind } from '../../compiler/design-ast.ts'
import type { Emitter, EmitContext, EmitResult } from '../types.ts'
import { elem, setProp, addChild, printElement, type SElement } from './ir.ts'
import { lowerFlexLike } from './lower-flex.ts'
import { lowerBox } from './lower-box.ts'
import { lowerText } from './lower-text.ts'

export interface SlintEmitContext extends EmitContext {
  /** Path used for `import { Tokens } from "<here>";`. Relative to the
   *  emitted .slint file. Required when the AST references token paths;
   *  optional otherwise. */
  tokensImportPath?: string
  /** Path used for `import { PixpecText } from "<here>";`. Required when
   *  the AST contains DText (text emission resolves to PixpecText, the
   *  generated wrapper that hosts the Y-shift correction table). */
  pixpecTextImportPath?: string
  /** Optional .ttf paths to register at the top of the file. Each becomes
   *  one `import "...";` line. Resolution is the consumer's responsibility. */
  fontImports?: string[]
}

function lowerNode(n: DNode): SElement {
  switch (n.kind) {
    case NodeKind.Flex:
    case NodeKind.Stack: return lowerFlexLike(n as DFlex | DStack, lowerNode)
    case NodeKind.Box: return lowerBox(n as DBox, lowerNode)
    case NodeKind.Text: return lowerText(n as DText)
    default:
      throw new Error(`slint emitter: unsupported DNode kind "${n.kind}" (${n.sourceName} ${n.sourceId})`)
  }
}

function rootSize(root: DNode): { width?: number; height?: number } {
  if ('width' in root && root.width && typeof root.width === 'object' && 'value' in root.width) {
    const w = root.width.value
    if ('height' in root && root.height && typeof root.height === 'object' && 'value' in root.height) {
      return { width: w, height: root.height.value }
    }
    return { width: w }
  }
  return {}
}

export const slintEmitter: Emitter = {
  name: 'slint',
  description: 'Slint markup — Window-wrapped components with token-driven design system.',
  emit(root: DNode, ctx: EmitContext): EmitResult {
    const ext = ctx as SlintEmitContext
    const { width, height } = rootSize(root)
    const lowered = lowerNode(root)

    const win = elem('Window')
    if (width !== undefined) setProp(win, 'width', `${width}px`)
    if (height !== undefined) setProp(win, 'height', `${height}px`)
    setProp(win, 'background', 'white')
    addChild(win, lowered)

    const lines: string[] = []
    lines.push(`// AUTO-GENERATED by pixpec slint emitter. Source: ${root.sourceId} (${root.sourceName})`)
    for (const f of ext.fontImports ?? []) lines.push(`import ${JSON.stringify(f)};`)
    if (ext.tokensImportPath) lines.push(`import { Tokens } from ${JSON.stringify(ext.tokensImportPath)};`)
    if (ext.pixpecTextImportPath) lines.push(`import { PixpecText } from ${JSON.stringify(ext.pixpecTextImportPath)};`)
    if ((ext.fontImports?.length ?? 0) > 0 || ext.tokensImportPath || ext.pixpecTextImportPath) lines.push('')
    lines.push(`export component ${ctx.componentName} inherits ${printElement(win)}`)
    lines.push('')

    return { source: lines.join('\n'), fileExtension: 'slint' }
  },
}
