import type {
  DBox,
  DFlex,
  DImage,
  DInstance,
  DNode,
  DShape,
  DStack,
  DText,
  DUnknown,
  DVector,
  Color,
  Size,
} from '../../compiler/design-ast.ts'
import {
  Align,
  FlowDirection,
  Justify,
  NodeKind,
  Positioning,
  ShapeKind,
  Sizing,
  TextAlign,
} from '../../compiler/design-ast.ts'
import type { CodegenContext, CodegenResult } from '../types.ts'

interface Ctx {
  tokenValueMap: Record<string, number>
}

export function codegenGpui(root: DNode, ctx: CodegenContext): CodegenResult {
  const cgCtx: Ctx = {
    tokenValueMap: ctx.designSystem?.tokenValues ?? {},
  }
  const body = emitNode(root, cgCtx, 2)
  return {
    fileExtension: 'rs',
    source: `// AUTO-GENERATED by pixpec gpui target.
// Source: ${ctx.sourceId ?? root.sourceId}

use gpui::{div, px, rgba, rgb, AnyElement, Context, IntoElement, Render, Window};
use gpui::prelude::*;

pub struct Generated;

impl Render for Generated {
    fn render(&mut self, _window: &mut Window, _cx: &mut Context<Self>) -> impl IntoElement {
${body}
    }
}
`,
  }
}

function emitNode(n: DNode, ctx: Ctx, indent: number): string {
  switch (n.kind) {
    case NodeKind.Flex:
    case NodeKind.Stack:
    case NodeKind.Box:
      return emitContainer(n, ctx, indent)
    case NodeKind.Text:
      return emitText(n, ctx, indent)
    case NodeKind.Shape:
      return emitShape(n, ctx, indent)
    case NodeKind.Vector:
      return emitVector(n, ctx, indent)
    case NodeKind.Image:
      return emitImage(n, ctx, indent)
    case NodeKind.Instance:
      return emitInstance(n, ctx, indent)
    case NodeKind.Unknown:
      return emitUnknown(n, ctx, indent)
  }
}

function emitContainer(n: DFlex | DStack | DBox, ctx: Ctx, indent: number): string {
  const lines = [`${pad(indent)}div()`]
  const direction =
    n.kind === NodeKind.Flex
      ? FlowDirection.Row
      : n.kind === NodeKind.Stack
        ? FlowDirection.Column
        : undefined
  if (direction) {
    lines.push(`${pad(indent + 1)}.flex()`)
    if (direction === FlowDirection.Column) lines.push(`${pad(indent + 1)}.flex_col()`)
  }
  addSizing(lines, n, ctx, indent + 1)
  addContainerStyles(lines, n, ctx, indent + 1)
  if (direction) {
    const flex = n as DFlex | DStack
    if (flex.gap) lines.push(`${pad(indent + 1)}.gap(${sizeExpr(flex.gap, ctx)})`)
    if (flex.align === Align.Center) lines.push(`${pad(indent + 1)}.items_center()`)
    else if (flex.align === Align.End) lines.push(`${pad(indent + 1)}.items_end()`)
    else lines.push(`${pad(indent + 1)}.items_start()`)
    if (flex.justify === Justify.Center) lines.push(`${pad(indent + 1)}.justify_center()`)
    else if (flex.justify === Justify.End) lines.push(`${pad(indent + 1)}.justify_end()`)
    else if (flex.justify === Justify.SpaceBetween) lines.push(`${pad(indent + 1)}.justify_between()`)
  }
  for (const child of n.children) {
    lines.push(`${pad(indent + 1)}.child(${childExpr(child, ctx, indent + 2)})`)
  }
  return lines.join('\n')
}

function emitText(n: DText, ctx: Ctx, indent: number): string {
  const lines = [`${pad(indent)}div()`]
  lines.push(`${pad(indent + 1)}.child(${str(n.content)})`)
  lines.push(`${pad(indent + 1)}.text_color(${colorExpr(n.color)})`)
  lines.push(`${pad(indent + 1)}.text_size(${sizeExpr(n.fontSize, ctx)})`)
  if (n.textAlign === TextAlign.Center) lines.push(`${pad(indent + 1)}.text_center()`)
  else if (n.textAlign === TextAlign.Right) lines.push(`${pad(indent + 1)}.text_right()`)
  return lines.join('\n')
}

function emitShape(n: DShape, ctx: Ctx, indent: number): string {
  const lines = [`${pad(indent)}div()`]
  lines.push(`${pad(indent + 1)}.w(${sizeExpr(n.width, ctx)})`)
  lines.push(`${pad(indent + 1)}.h(${sizeExpr(n.height, ctx)})`)
  if (n.fill) lines.push(`${pad(indent + 1)}.bg(${colorExpr(n.fill)})`)
  if (n.shape === ShapeKind.Ellipse) lines.push(`${pad(indent + 1)}.rounded_full()`)
  if (n.opacity !== undefined) lines.push(`${pad(indent + 1)}.opacity(${num(n.opacity)})`)
  return lines.join('\n')
}

function emitVector(_n: DVector, _ctx: Ctx, indent: number): string {
  return `${pad(indent)}div()`
}

function emitImage(_n: DImage, _ctx: Ctx, indent: number): string {
  return `${pad(indent)}div()`
}

function emitInstance(n: DInstance, ctx: Ctx, indent: number): string {
  const lines = [`${pad(indent)}div()`]
  if (n.width) lines.push(`${pad(indent + 1)}.w(${sizeExpr(n.width, ctx)})`)
  if (n.height) lines.push(`${pad(indent + 1)}.h(${sizeExpr(n.height, ctx)})`)
  return lines.join('\n')
}

function emitUnknown(n: DUnknown, ctx: Ctx, indent: number): string {
  return [
    `${pad(indent)}div()`,
    `${pad(indent + 1)}.w(${sizeExpr(n.width, ctx)})`,
    `${pad(indent + 1)}.h(${sizeExpr(n.height, ctx)})`,
  ].join('\n')
}

function childExpr(n: DNode, ctx: Ctx, indent: number): string {
  const rendered = emitNode(n, ctx, indent)
  if (n.visibilityBinding) {
    return `if true { ${rendered.trim()} } else { div() }`
  }
  if (n.positioning === Positioning.Absolute) {
    return rendered
  }
  return rendered
}

function addSizing(lines: string[], n: DFlex | DStack | DBox, ctx: Ctx, indent: number): void {
  if (n.sizing?.horizontal === Sizing.Fill) lines.push(`${pad(indent)}.w_full()`)
  else if (n.width) lines.push(`${pad(indent)}.w(${sizeExpr(n.width, ctx)})`)
  if (n.sizing?.vertical === Sizing.Fill) lines.push(`${pad(indent)}.h_full()`)
  else if (n.height) lines.push(`${pad(indent)}.h(${sizeExpr(n.height, ctx)})`)
}

function addContainerStyles(
  lines: string[],
  n: DFlex | DStack | DBox,
  ctx: Ctx,
  indent: number,
): void {
  if (n.background) lines.push(`${pad(indent)}.bg(${colorExpr(n.background)})`)
  if (n.padding) {
    lines.push(`${pad(indent)}.pt(${sizeExpr(n.padding.top, ctx)})`)
    lines.push(`${pad(indent)}.pr(${sizeExpr(n.padding.right, ctx)})`)
    lines.push(`${pad(indent)}.pb(${sizeExpr(n.padding.bottom, ctx)})`)
    lines.push(`${pad(indent)}.pl(${sizeExpr(n.padding.left, ctx)})`)
  }
  if (n.cornerRadius && !('tl' in n.cornerRadius)) {
    lines.push(`${pad(indent)}.rounded(${sizeExpr(n.cornerRadius, ctx)})`)
  }
  if (n.opacity !== undefined) lines.push(`${pad(indent)}.opacity(${num(n.opacity)})`)
  if (n.clip) lines.push(`${pad(indent)}.overflow_hidden()`)
}

function sizeExpr(size: Size, ctx: Ctx): string {
  if ('tokenPath' in size) return `px(${num(ctx.tokenValueMap[size.tokenPath] ?? 0)})`
  return `px(${num(size.value)})`
}

function colorExpr(color: Color): string {
  if ('tokenPath' in color) return 'rgb(0x000000)'
  const rgbaMatch = /^rgba\((\d+),(\d+),(\d+),([0-9.]+)\)$/.exec(color.color)
  if (rgbaMatch) {
    const [, r, g, b, a] = rgbaMatch
    const alpha = Math.round(Number(a) * 255)
    return `rgba(0x${hex(Number(r))}${hex(Number(g))}${hex(Number(b))}${hex(alpha)})`
  }
  const hexMatch = /^#([0-9a-fA-F]{6})$/.exec(color.color)
  if (hexMatch) return `rgb(0x${hexMatch[1]})`
  return 'rgb(0x000000)'
}

function pad(level: number): string {
  return '    '.repeat(level)
}

function str(value: string): string {
  return JSON.stringify(value)
}

function num(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${+value.toFixed(6)}`
}

function hex(value: number): string {
  return Math.max(0, Math.min(255, value)).toString(16).padStart(2, '0')
}
