import type { DNode } from '../../compiler/design-ast.ts'
import type { CodegenContext, CodegenResult } from '../types.ts'
import type { GpuiEmitContext } from './emit/context.ts'
import { emitNode } from './emit/node.ts'

export async function codegenGpui(root: DNode, ctx: CodegenContext): Promise<CodegenResult> {
  const emitCtx: GpuiEmitContext = {
    tokenValueMap: ctx.designSystem?.tokenValues ?? {},
    tokenColorMap: ctx.designSystem?.tokenColors ?? {},
    renderScale: ctx.renderScale ?? 1,
    fonts: parseFontManifest(ctx.designSystem?.fonts),
    assets: new Map(),
  }
  const body = await emitNode(root, emitCtx, 2)
  const renderScale = Number.isFinite(emitCtx.renderScale) ? emitCtx.renderScale : 1

  return {
    fileExtension: 'rs',
    source: `// AUTO-GENERATED by pixpec gpui target.
// Source: ${ctx.sourceId ?? root.sourceId}

#![allow(unused_imports)]

use gpui::{div, img, px, rgba, rgb, Context, FontWeight, IntoElement, ObjectFit, Render, Window};
use gpui::prelude::*;

pub struct Generated;

pub const PIXPEC_RENDER_SCALE: f32 = ${rustFloat(renderScale)};

impl Render for Generated {
    fn render(&mut self, _window: &mut Window, _cx: &mut Context<Self>) -> impl IntoElement {
${body}
    }
}
`,
    sidecars: [...emitCtx.assets.values()],
  }
}

function rustFloat(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${+value.toFixed(6)}`
}

function parseFontManifest(value: unknown): GpuiEmitContext['fonts'] {
  if (!value || typeof value !== 'object') return undefined
  const fonts = (value as { fonts?: unknown }).fonts
  if (!Array.isArray(fonts)) return undefined
  return {
    fonts: fonts
      .filter((font): font is { family: string; xShift?: Record<string, number>; yShift?: Record<string, number> } =>
        !!font &&
        typeof font === 'object' &&
        typeof (font as { family?: unknown }).family === 'string',
      )
      .map((font) => ({
        family: font.family,
        xShift: numericRecord(font.xShift),
        yShift: numericRecord(font.yShift),
      })),
  }
}

function numericRecord(value: unknown): Record<string, number> | undefined {
  if (!value || typeof value !== 'object') return undefined
  const entries = Object.entries(value)
    .filter((entry): entry is [string, number] => typeof entry[1] === 'number')
  return entries.length ? Object.fromEntries(entries) : undefined
}
