/**
 * Generator CLI: walk a figma node, write a real pixpec component to
 * src/components/<Name>/ that the runner can verify like any other.
 *
 *   pnpm pixpec generate <nodeId> [--name Generated] [--tab Sandbox]
 *
 * Produces:
 *   src/components/<Name>/
 *     impl.tsx     # generated React FC (the component under test)
 *     index.ts     # defineComponent({name, cases, noise: ()=>1e6})
 *     cases.ts     # single Case pointing to the source figma nodeId
 *
 * After generation, run the standard pipeline to verify:
 *   pnpm pixpec dump-chromium <Name>
 *   pnpm pixpec dump-figma <Name> [tab]
 *   pnpm pixpec-measure .pixpec-out/<Name>
 *
 * Goal: max Lab dE/px < 1 across generated nodes. If higher, the
 * recognizer/codegen needs to refine (or a missing figma binding to
 * register).
 */
import { writeFile, mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { loadConfig } from '../init.ts'
import type { Component } from '../types.ts'
import { walk, buildRegistry } from './walker.ts'
import { generate } from './codegen.ts'
import type { IRNode } from './ir.ts'

const isComponent = (v: unknown): v is Component<unknown> =>
  !!v && typeof v === 'object' && 'name' in v && 'cases' in v && 'noise' in v

export async function runGenerate(
  nodeId: string,
  opts: { tab?: string; name?: string } = {},
): Promise<{ jsx: string; ir: IRNode; componentDir: string; componentName: string }> {
  const { cfg, root } = await loadConfig()
  if (!cfg.cfigmaBin) throw new Error('pixpec.toml: cfigmaBin required')
  const componentName = opts.name ?? `Gen_${nodeId.replace(':', '_')}`
  const componentsDir = cfg.componentsDir ?? 'src/components'
  const componentDir = resolve(root, componentsDir, componentName)

  // Discover all components from project's src/index.ts (their figma bindings).
  const registryMod = (await import(resolve(root, 'src/index.ts'))) as Record<string, unknown>
  const components = Object.values(registryMod).filter(isComponent)
  console.log(`[generate] loaded ${components.length} components, ${components.filter(c => c.figma).length} with figma bindings`)
  const registry = buildRegistry(components)

  const tab = opts.tab ?? cfg.tabPattern
  const ir = await walk({ cfigmaBin: cfg.cfigmaBin, tab, nodeId, registry })

  // Get the wrapper dim from the source frame so the generated component
  // can be rendered into a fixed-size box for dim parity.
  const wrapper = await getNodeDim(cfg.cfigmaBin, tab, nodeId)
  const jsx = generate(ir, components)
  const fileKey = await getFileKey(cfg.cfigmaBin, tab)

  await mkdir(componentDir, { recursive: true })
  // Generator emits a full self-contained tsx (with FC type, Generated, impl).
  await writeFile(resolve(componentDir, 'impl.tsx'),
`/**
 * AUTO-GENERATED by \`pixpec generate ${nodeId}\`.
 * Source figma node: ${nodeId}
 */
${jsx}export interface GeneratedProps {}
`)
  await writeFile(resolve(componentDir, 'cases.ts'),
`// AUTO-GENERATED by \`pixpec generate ${nodeId}\`.
import type { Case } from 'pixpec/spec'
import type { GeneratedProps } from './impl.tsx'

export const cases: Case<GeneratedProps>[] = [
  {
    name: ${JSON.stringify(`${componentName}_main`)},
    props: {},
    fileKey: ${JSON.stringify(fileKey)},
    nodeId: ${JSON.stringify(nodeId)},
    wrapper: ${JSON.stringify(wrapper)},
  },
]
`)
  await writeFile(resolve(componentDir, 'index.ts'),
`// AUTO-GENERATED.
import { defineComponent } from 'pixpec/spec'
import { cases } from './cases.ts'
import type { GeneratedProps } from './impl.tsx'

export type { GeneratedProps }

export const ${componentName} = defineComponent<GeneratedProps>({
  name: ${JSON.stringify(componentName)},
  cases,
  noise: () => 1e6, // generator output: pass-through, dE checked manually
})
`)
  console.log(`[generate] wrote → ${componentDir}`)
  console.log(`\nNext steps:`)
  console.log(`  1. Add \`export { ${componentName} } from './components/${componentName}/index.ts'\` to src/index.ts`)
  console.log(`  2. pnpm pixpec dump-chromium ${componentName}`)
  console.log(`  3. pnpm pixpec dump-figma ${componentName} ${tab}`)
  console.log(`  4. pnpm pixpec-measure .pixpec-out/${componentName}`)
  return { jsx, ir, componentDir, componentName }
}

/** Query node dim via cfigma exec (small one-shot). */
async function getNodeDim(cfigmaBin: string, tab: string, nodeId: string): Promise<{ width: number; height: number; padding: number; bg: string }> {
  const { execFile } = await import('node:child_process')
  const { promisify } = await import('node:util')
  const execFileAsync = promisify(execFile)
  const { stdout } = await execFileAsync(cfigmaBin,
    ['--tab', tab, 'exec', `const n = await figma.getNodeByIdAsync(${JSON.stringify(nodeId)}); return { width: n.width, height: n.height };`],
    { encoding: 'utf8',
      env: { ...process.env, CFIGMA_CDP_PORT: process.env.CFIGMA_CDP_PORT ?? '9222' } })
  const dim = JSON.parse(stdout) as { width: number; height: number }
  return { ...dim, padding: 0, bg: '#ffffff' }
}

async function getFileKey(cfigmaBin: string, tab: string): Promise<string> {
  const { execFileSync } = await import('node:child_process')
  const out = execFileSync(cfigmaBin, ['tabs'], { encoding: 'utf8',
    env: { ...process.env, CFIGMA_CDP_PORT: process.env.CFIGMA_CDP_PORT ?? '9222' } })
  const m = out.split('\n').find(l => l.toLowerCase().includes(tab.toLowerCase()))
  const k = m?.match(/key=(\w+)/)
  if (!k) throw new Error(`could not resolve fileKey for tab '${tab}'`)
  return k[1]
}
