import { mkdir, readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import type { Component } from "./types.ts";
import { splitFigmaId } from "./types.ts";
import { safeCaptureId } from "./capture/resolve.ts";
import { componentPixpecDir } from "./capture/index.ts";
import { writeRggMaps } from "./rgg.ts";

export interface VerifyReportRecord {
  case: string;
  dE00: number;
  dE00_max: number;
  blob_max_size: number;
  blob_max_bbox?: [number, number, number, number] | null;
  blobs?: Array<{
    threshold: number;
    max_size: number;
    max_bbox?: [number, number, number, number] | null;
  }>;
  artifacts: { figma: string; impl: string };
}

export interface VerifyTargetReport {
  target: string;
  maxBlob: number;
  records: VerifyReportRecord[];
  failed: VerifyReportRecord[];
}

export interface DetachedUsageReport {
  figmaId: string;
  reason: string;
  fields: string[];
  targets?: Array<{ nodeId: string; fields: string[] }>;
}

export async function writeComponentReport(opts: {
  componentName: string;
  componentDir: string;
  component: Component<unknown>;
  targets?: string[];
  verifyTargets?: VerifyTargetReport[];
  detachedUsages?: DetachedUsageReport[];
}): Promise<void> {
  const propsScheme = await readOptional(resolve(opts.componentDir, "schema.ts"));
  const representative = findRepresentativeCase(opts.component);
  const targetNames =
    opts.targets ??
    opts.verifyTargets?.map((target) => target.target) ??
    [];
  const lines: string[] = [];
  lines.push(`# ${opts.componentName}`);
  lines.push("");
  lines.push("> Generated by Pixpec. Heavy capture artifacts live under `.pixpec/`.");
  lines.push("");
  lines.push("## Representative Visual");
  lines.push("");
  if (representative) {
    const safeId = safeCaptureId(representative.figmaId);
    lines.push(`- Figma: ${figmaLink(representative.figmaId)}`);
    lines.push("");
    lines.push(imageBlock("Figma source", `.pixpec/src/figma/${safeId}.png`));
    for (const target of targetNames) {
      lines.push("");
      lines.push(imageBlock(`${target} destination`, `.pixpec/dst/${target}/${safeId}.png`));
    }
  } else {
    lines.push("_No cases found._");
  }
  lines.push("");
  lines.push("## Props Scheme");
  lines.push("");
  if (propsScheme.trim()) {
    lines.push("```ts");
    lines.push(propsScheme.trimEnd());
    lines.push("```");
  } else {
    lines.push("_No schema.ts found._");
  }
  lines.push("");
  lines.push("## Figma Links");
  lines.push("");
  for (const v of opts.component.variants) {
    const main = (v.usecases ?? []).find((u) => u.isMainCase) ?? v.usecases?.[0];
    if (!main) continue;
    lines.push(`- \`${main.figmaId}\`: ${figmaLink(main.figmaId)}`);
  }
  lines.push("");
  lines.push("## Verification Failures");
  lines.push("");
  if (!opts.verifyTargets || opts.verifyTargets.length === 0) {
    lines.push("_No verification run recorded yet._");
  } else {
    for (const target of opts.verifyTargets) {
      lines.push(`### ${target.target}`);
      lines.push("");
      if (target.failed.length === 0) {
        lines.push(`All ${target.records.length} cases passed.`);
        lines.push("");
        continue;
      }
      lines.push(`Failed ${target.failed.length}/${target.records.length} cases. Max blob threshold: ${target.maxBlob}.`);
      lines.push("");
      for (const record of target.failed) {
        lines.push(`#### \`${record.case}\``);
        lines.push("");
        lines.push(`- Figma: ${figmaLinkFromSafeCase(record.case)}`);
        lines.push(`- dE00 sum: ${record.dE00.toFixed(0)}`);
        lines.push(`- dE00 max: ${record.dE00_max.toFixed(2)}`);
        lines.push(`- blob max size: ${record.blob_max_size}`);
        if (record.blob_max_bbox) {
          lines.push(`- blob bbox: \`${record.blob_max_bbox.join(", ")}\``);
        }
        if (record.blobs?.length) {
          lines.push(`- E00 blobs: ${record.blobs.map((b) => `>${b.threshold}: ${b.max_size}`).join(", ")}`);
        }
        lines.push("");
        lines.push(imageBlock("Figma", rel(opts.componentDir, record.artifacts.figma)));
        lines.push("");
        lines.push(imageBlock("Destination", rel(opts.componentDir, record.artifacts.impl)));
        lines.push("");
        const rggBase = `.pixpec/verify/figma__${target.target}/rgg/${record.case}`;
        lines.push(imageBlock("RGG hue", `${rggBase}/rgg-h.png`));
        lines.push("");
        lines.push(imageBlock("RGG saturation", `${rggBase}/rgg-s.png`));
        lines.push("");
        lines.push(imageBlock("RGG value", `${rggBase}/rgg-v.png`));
        lines.push("");
      }
    }
  }
  lines.push("");
  lines.push("## Detached Usages");
  lines.push("");
  if (!opts.detachedUsages || opts.detachedUsages.length === 0) {
    lines.push("_No detached usages recorded._");
  } else {
    lines.push(
      "These usages contain overrides that are not represented by promoted component props. Pixpec excludes them from component cases; they should be rendered as detached raw IR when used in views.",
    );
    lines.push("");
    lines.push(`Total detached usages: ${opts.detachedUsages.length}`);
    const fieldCounts = countBy(opts.detachedUsages.flatMap((u) => u.fields));
    const targetCounts = countBy(
      opts.detachedUsages.flatMap((u) =>
        (u.targets ?? []).map(
          (t) => `${t.nodeId} (${t.fields.slice().sort().join(", ")})`,
        ),
      ),
    );
    lines.push(
      `Fields: ${formatCountSummary(fieldCounts, (name) => `\`${name}\``)}`,
    );
    lines.push(`Targets: ${formatCountSummary(targetCounts, (name) => name)}`);
    lines.push("");
    const shown = opts.detachedUsages.slice(0, 50);
    if (opts.detachedUsages.length > shown.length) {
      lines.push(
        `Showing first ${shown.length} detached usages; ${opts.detachedUsages.length - shown.length} more omitted.`,
      );
      lines.push("");
    }
    for (const usage of shown) {
      lines.push(`- \`${usage.figmaId}\`: ${figmaLink(usage.figmaId)}`);
      lines.push(`  - reason: ${usage.reason}`);
      lines.push(`  - uncovered fields: ${usage.fields.map((f) => `\`${f}\``).join(", ")}`);
      if (usage.targets && usage.targets.length > 0) {
        lines.push(
          `  - targets: ${usage.targets
            .map((t) => `${t.nodeId} (${t.fields.map((f) => `\`${f}\``).join(", ")})`)
            .join("; ")}`,
        );
      }
    }
  }
  await writeFile(resolve(opts.componentDir, "pixpec.md"), lines.join("\n") + "\n");
}

function countBy(values: string[]): Array<{ name: string; count: number }> {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}

function formatCountSummary(
  counts: Array<{ name: string; count: number }>,
  formatName: (name: string) => string,
): string {
  if (counts.length === 0) return "_none_";
  const shown = counts
    .slice(0, 12)
    .map((c) => `${formatName(c.name)}=${c.count}`);
  const more = counts.length - shown.length;
  return more > 0 ? `${shown.join(", ")}, +${more} more` : shown.join(", ");
}

export async function writeRggForFailedCases(opts: {
  componentDir: string;
  target: string;
  failed: VerifyReportRecord[];
}): Promise<void> {
  for (const record of opts.failed) {
    const outDir = resolve(
      componentPixpecDir(opts.componentDir),
      "verify",
      `figma__${opts.target}`,
      "rgg",
      record.case,
    );
    await mkdir(outDir, { recursive: true });
    await writeRggMaps(record.artifacts.figma, record.artifacts.impl, outDir, {
      shiftX: 0,
      shiftY: 0,
    });
  }
}

async function readOptional(path: string): Promise<string> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return "";
  }
}

function findRepresentativeCase(component: Component<unknown>) {
  for (const variant of component.variants) {
    const main = variant.usecases?.find((u) => u.isMainCase);
    if (main) return main;
  }
  return component.variants.flatMap((v) => v.usecases ?? [])[0];
}

function imageBlock(label: string, path: string): string {
  return `![${escapeMarkdown(label)}](${path})`;
}

function figmaLink(figmaId: string): string {
  const { fileKey, nodeId } = splitFigmaId(figmaId);
  return `https://www.figma.com/design/${encodeURIComponent(fileKey)}?node-id=${encodeURIComponent(nodeId.replace(/:/g, "-"))}`;
}

function figmaLinkFromSafeCase(caseId: string): string {
  const i = caseId.indexOf("_");
  if (i < 0) return caseId;
  const fileKey = caseId.slice(0, i);
  const nodeId = caseId.slice(i + 1).replace(/_/g, "-");
  return `https://www.figma.com/design/${encodeURIComponent(fileKey)}?node-id=${encodeURIComponent(nodeId)}`;
}

function rel(fromDir: string, toPath: string): string {
  return relative(fromDir, toPath).replace(/\\/g, "/");
}

function escapeMarkdown(s: string): string {
  return s.replace(/]/g, "\\]");
}
